#!/bin/bash
###########################################################################
# Author:	Jane Curry
# Date:		October 14th 2011
# Modified:
#
# Expects 2 parameters which it simply echos
###########################################################################
#set -x


echo "$1" "$2 $3 $4"
echo `date` $1 $2  $3 $4 > /tmp/mywrapper_script.log

